Practice branch to help solve testData() problem.
jtian98/CodeU-Spring-2018 pull request #14
Opened 2018-04-06 05:20 UTC by yourboyoch

So I was trying to integrate the testData function into the testData page and for some reason, nothing comes up when I try to create a conversation from the Practice.txt file. Also, although I had all the code for the random conversation generator commented out they still appear when the site is launched, I'm thinking there's something wrong with the Datastore that stores test Data. I was thinking that might have something to do with our `writeThrough()` function. 
Another possible reason I think `Practice.txt` might be failing to make a conversation is that the file cannot be found. I previously had a `try()` `catch()` block within my `testData()` method that captured all the code with `testData()` in the `try()` block but the `FileNotFoundException` kept getting triggered so maybe my file isn't getting found? The Practice file is within my CodeU-Spring-2018 directory. If anyone needs any clarification just ask I know everything I wrote is kinda jargon right now.

2018-04-06 09:32 UTC, kevmo314 requested changes

2018-04-06 09:32 UTC, kevmo314 commented on .metadata/.log
> +!SESSION 2018-03-26 19:38:04.461 -----------------------------------------------
Can you `.gitignore` the `.metadata` directory?

2018-04-06 09:32 UTC, kevmo314 commented on src/main/java/codeu/model/store/basic/DefaultDataStore.java
> +		testData(fileName);
Won't this read the data every single time `getAllUsers()` is called? We should only read it once ideally.

2018-04-06 20:06 UTC, philipcori commented
DefaultDataStore generates the random data and writes it through to PersistentDataStore. The loadUsers() method in PersistantDataStore is what loads the Users, Messages, and Conversations when the app is restarted. To clear all stored data though, just run mvn clean.

2018-04-07 05:39 UTC, yourboyoch commented on .metadata/.log
> +!SESSION 2018-03-26 19:38:04.461 -----------------------------------------------
don't worry Kevin I'm never merging this branch, I just wanted to get the code up so you could look at it

2018-04-07 05:49 UTC, yourboyoch commented on .metadata/.log
> +!SESSION 2018-03-26 19:38:04.461 -----------------------------------------------
:(( actually I forgot to stash my changes before I switched branches so I might have to copy and paste this after all.

2018-04-14 21:24 UTC, closed without merging